### ISSUE TITLE
3D Keypoint Driver SMPLX-unity

### ISSUE THREAD

**Issue by xiaoyudanaa** [sangho0n/Realtime_SMPLX_Unity#1]
### Description

Hello,
I found your open-source project very inspiring, and I greatly appreciate your contribution. I encountered issues with pose distortion while using TensorRT for real-time pose data streaming to drive Unity. I noticed that you used a 3D KP+lookup method in your project. Could you please explain why you chose this method? Additionally, what are your insights on the pose distortion issues we are experiencing when using pose data to drive SMPL-X in Unity? I look forward to your response.
Thank you.

**Comment by sangho0n** [comment]
Hello, thank you for your interest.

First of all, I would like to mention that this project is quite outdated. Recently, lightweight models that can infer SMPL meshes in real-time have been developed, and it's now possible to convert these models to ONNX and use them for real-time inference in Unity.

While I’m not entirely sure what you mean by the "3D KP + lookup method," I’ll answer based on my understanding, which I assume refers to manipulating the SMPL mesh using 3D key points.

Let me address your two questions:

- **Could you please explain why you chose this method?**
At the time, it was challenging to run a model that infers the SMPLX mesh in real-time within Unity. Therefore, I had to compromise on the accuracy of the shape parameters and use a different pose estimation model. As you may know, the joints in the pose estimation model I used (Mediapipe) do not perfectly match the joints in SMPLX. Thus, I generally treated joints with the same names as equivalent, and for joints present in SMPL but not in Mediapipe, I interpolated them using nearby joints.

- **What are your insights on the pose distortion issues?**
As mentioned above, the joints used in SMPLX and the joints from the models we used do not perfectly align. Additionally, since SMPLX is a parametric model, it requires not only joint information but also shape parameters to infer poses that closely resemble reality without distortion.

As I mentioned earlier, if you’re looking for a lightweight model to infer SMPLX meshes, you can convert it to ONNX and use it in Unity.

I hope this helps, even if my response is a bit late.
Thnk you.

**Comment by kesdogan** [comment]
What lightweight models are you thinking of for inferring SMPL meshes in real-time? I have done some literature search here and did not find anything substantial. Would be great to know! What I want to achieve is to merely get the SMPL pose parameters for a person in real time.
